name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        goos: [darwin, linux, windows]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v3

    - uses: actions-ecosystem/action-release-label@v1
      id: release-label
      if: ${{ github.event.pull_request.merged == true }}

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      if: ${{ steps.release-label.outputs.level != null }}

    - uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      if: ${{ steps.release-label.outputs.level != null }}
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: ${{ steps.release-label.outputs.level }}

    - uses: actions-ecosystem/action-push-tag@v1
      if: ${{ steps.release-label.outputs.level != null }}
      with:
        tag: ${{ steps.bump-semver.outputs.new_version }}
        message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Set up swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: Build
      run: GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build -v --ldflags="-X ${PACKAGE}/version.Version=${{ steps.bump-semver.outputs.new_version }} -X ${PACKAGE}/version.BuildTimestamp=${{ steps.date.outputs.date }}"

    - name: Test
      run: go test -v ./...
